apiVersion: policy/v1beta1 # todo for unclear reason this manifest is not caught by helm lint...
kind: PodSecurityPolicy
metadata:
  name: {{ include "testchart-deprecated.fullname" . }}-psp
spec:
  fsGroup:
    rule: RunAsAny
  privileged: true
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
    - '*'
  allowedCapabilities:
    - '*'
  hostPID: true
  hostIPC: true
  hostNetwork: true
  hostPorts:
    - min: 1
      max: 65536
