# https://chartmuseum.com/docs/#configuration
# https://github.com/chartmuseum/auth-server-example/blob/master/docker-compose.yml
# https://github.com/helm/chartmuseum/tree/main
# https://github.com/helm/chartmuseum/blob/main/pkg/config/vars.go

version: "3.9"
services: # multiple chart museum deployments since cannot enable both token and basic auth
  chartmuseum-basicauth:
    image: "ghcr.io/helm/chartmuseum:v0.14.0"
    environment:
      - DEBUG=1
      - STORAGE=local
      - STORAGE_LOCAL_ROOTDIR=/tmp # ephemeral: test-only
      - BASIC_AUTH=1
      - BASIC_AUTH_USER=test
      - BASIC_AUTH_PASS=test
    restart: unless-stopped
    networks:
      - cm
    ports:
      - "8081:8080"
    expose:
      - 8080
  chartmuseum-token:
    image: "ghcr.io/helm/chartmuseum:v0.14.0"
    volumes:
      - ./authserver/config:/config:ro
    environment:
      - DEBUG=1
      - STORAGE=local
      - STORAGE_LOCAL_ROOTDIR=/tmp # ephemeral: test-only
      - BEARER_AUTH=1
      - AUTH_REALM=http://localhost:5001/oauth/token
      - AUTH_SERVICE=localhost:5001
      - AUTH_CERT_PATH=/config/server.pem
    restart: unless-stopped
    networks:
      - cm
    ports:
      - "8082:8080"
    expose:
      - 8080
  authserver:
    image: "golang:1.11"
    ports:
      - "5001:5001"
    command: "go run main.go"
    working_dir: "/go/src/github.com/chartmuseum/auth-server-example/authserver"
    volumes:
      - "./authserver/authserver:/go/src/github.com/chartmuseum/auth-server-example/authserver:ro"
      - "./authserver/config:/go/src/github.com/chartmuseum/auth-server-example/config:ro"

networks:
  cm:
