# https://chartmuseum.com/docs/#configuration
# https://github.com/chartmuseum/auth-server-example/blob/master/docker-compose.yml
# todo setup this authserver for bearer auth
version: "3.9"
services:
  chartmuseum:
    container_name: chartmuseum
    image: "ghcr.io/helm/chartmuseum:v0.14.0"
#    command:
#      - --config
#      - /etc/config.yaml
    volumes:
      - cm_db:/charts
    environment:
      - DEBUG=1
      - STORAGE=local
      - STORAGE_LOCAL_ROOTDIR=/charts
      - BASIC_AUTH_USER=test
      - BASIC_AUTH_PASS=test
#      - BEARER_AUTH=1
#      - AUTH_REALM=http://localhost:5001/oauth/token
#      - AUTH_SERVICE=localhost:5001
#      - AUTH_CERT_PATH=/config/server.pem
    restart: unless-stopped
    networks:
      - cm
    ports:
      - "8080:8080"
    expose:
      - 8080
#  authserver:
#    image: "golang:1.11"
#    ports:
#      - "5001:5001"
#    command: "go run main.go"
#    working_dir: "/go/src/github.com/chartmuseum/auth-server-example/authserver"
#    volumes:
#      - "./authserver:/go/src/github.com/chartmuseum/auth-server-example/authserver:ro"
#      - "./config:/go/src/github.com/chartmuseum/auth-server-example/config:ro"

volumes:
  cm_db:
    driver: local

networks:
  cm:
