name: Release

# https://docs.github.com/en/actions/configuring-and-managing-workflows/configuring-a-workflow#manually-running-a-workflow
on:
  push:
    tags:
      - 'v[0-9]+.*'

# fixme add requirement that tests from given commit hash already passed (so that we don't have to add test stage here)
jobs:
  test-release:
    uses: ./.github/workflows/test.yml
  release: # fixme wait for test-release it goes in parallel: https://github.com/kiemlicz/shelm/actions/runs/8270700884
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Setup sbt launcher
      uses: sbt/setup-sbt@v1
    - name: Release
      run: |
        echo "$PGP_KEY" | gpg --import
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        sbt publishSigned sonatypeRelease
      env:
        MVN_USERNAME: ${{ secrets.MVN_USERNAME }}
        MVN_TOKEN: ${{ secrets.MVN_TOKEN }}
        PGP_KEY_ID: ${{ secrets.PGP_KEY_ID }}
        PGP_KEY: ${{ secrets.PGP_KEY }}
