name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    name: ${{ matrix.java }}
    strategy:
      matrix:
        java: [11, 17]
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Setup environment
      run: |
        helm repo add stable https://charts.helm.sh/stable
        helm repo update
        echo "Helm setup complete, running Helm version:"
        helm version
        docker compose -f src/test/resources/registries/compose.yaml up -d
    - name: Run tests
      run: |
        sbt test
        sbt scripted

# > sbt "scripted shelm/simple" # runs single test